sudo: false

language: php

php:
  - 7.0
  - 7.1

matrix:
  allow_failures:
    - php: 7.1

cache:
  directories:
    - vendor
    - bin

before_script:
  - rm composer.lock
  - composer self-update
  - composer install
  - mkdir -p build/cov

script:
  - bin/phpcs
  - bin/phpmd src/ text phpmd.ruleset.xml
  - bin/phpunit --colors --coverage-php=build/coverage-integration.cov
  - bin/phpspec run --config phpspec.travis.yml

after_script:
  - bin/coveralls -v
